#!/usr/bin/env python3
"""Calculate abnormal read fractions in selected methylation regions.

This script compares per-read methylation values in a bin-level feature file
against reference boundaries provided for differentially methylated regions
(DMRs). For each matched region, it reports the number and fraction of reads
above the reference maximum and below the reference minimum.

The output column layout is intentionally compatible with the original internal
analysis script, while sensitive local paths and project-specific assumptions
have been removed.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Iterable, List

import pandas as pd


DEFAULT_FEATURE_COLUMNS = [
    "chr",
    "st",
    "end",
    "bin_mml",
    "average",
    "mhl",
    "transitions_score",
    "count",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Calculate the fraction of abnormal reads in DMRs by comparing "
            "per-read methylation values with reference min/max boundaries."
        )
    )
    parser.add_argument(
        "--feature-file",
        required=True,
        help=(
            "Tab-delimited bin-level methylation feature file generated by "
            "methyl_read_bin_profiler.py. The file is expected to contain "
            "chromosome, start, end, bin_mml, average, mhl, transitions_score, "
            "and count columns without a header."
        ),
    )
    parser.add_argument(
        "--dmr-file",
        required=True,
        help=(
            "Tab-delimited DMR/reference file. The first three columns should "
            "be chromosome, start, and end. The file must contain columns named "
            "ref_min and ref_max."
        ),
    )
    parser.add_argument(
        "--feature",
        default="average",
        choices=["average", "mhl", "transitions_score"],
        help="Read-level feature used for abnormal read counting. Default: average.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help=(
            "Output file path. If omitted, the output is written as "
            "<feature-file-basename>_abnormal_reads.txt in the current directory."
        ),
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print progress information.",
    )
    return parser.parse_args()


def setup_logging(verbose: bool = False) -> None:
    level = logging.INFO if verbose else logging.WARNING
    logging.basicConfig(format="[%(levelname)s] %(message)s", level=level)


def build_region_key(df: pd.DataFrame, chrom_col: str, start_col: str, end_col: str) -> pd.Series:
    """Create a region key in the format chr_start_end."""
    return (
        df[chrom_col].astype(str)
        + "_"
        + df[start_col].astype(str)
        + "_"
        + df[end_col].astype(str)
    )


def read_feature_file(feature_file: Path) -> pd.DataFrame:
    """Read the bin-level methylation feature file."""
    df = pd.read_csv(
        feature_file,
        sep="\t",
        header=None,
        names=DEFAULT_FEATURE_COLUMNS,
        dtype={"chr": str},
    )
    df["keys"] = build_region_key(df, "chr", "st", "end")
    return df


def read_dmr_file(dmr_file: Path) -> pd.DataFrame:
    """Read the DMR/reference file and add region keys."""
    dmr_df = pd.read_csv(dmr_file, sep="\t")
    if dmr_df.shape[1] < 3:
        raise ValueError("The DMR file must contain at least three columns: chr, start, and end.")
    required_cols = {"ref_min", "ref_max"}
    missing = required_cols.difference(dmr_df.columns)
    if missing:
        raise ValueError(
            "The DMR file must contain columns named ref_min and ref_max. "
            f"Missing: {', '.join(sorted(missing))}"
        )
    key_cols = dmr_df.columns[:3]
    dmr_df["keys"] = build_region_key(dmr_df, key_cols[0], key_cols[1], key_cols[2])
    return dmr_df


def extract_feature_values(feature_string: str, feature_name: str) -> List[float]:
    """Extract per-read numeric values from strings such as average:0.100:0.400."""
    if pd.isna(feature_string):
        return []
    feature_string = str(feature_string)
    prefix = f"{feature_name}:"
    if feature_string == feature_name:
        return []
    if feature_string.startswith(prefix):
        value_parts = feature_string[len(prefix) :].split(":")
    else:
        # Fallback for legacy files where the first token may still be the feature name.
        parts = feature_string.split(":")
        if parts and parts[0] == feature_name:
            value_parts = parts[1:]
        else:
            value_parts = parts
    values: List[float] = []
    for value in value_parts:
        if value == "" or value.upper() == "NA":
            continue
        values.append(float(value))
    return values


def count_abnormal(values: Iterable[float], ref_min: float, ref_max: float) -> pd.Series:
    """Count reads above ref_max and below ref_min."""
    value_list = list(values)
    if not value_list:
        return pd.Series(
            {
                "total": "NA",
                "count_above": "NA",
                "above_ratio": "NA",
                "count_below": "NA",
                "below_ratio": "NA",
            }
        )

    total = len(value_list)
    count_above = sum(1 for value in value_list if value > ref_max)
    count_below = sum(1 for value in value_list if value < ref_min)
    return pd.Series(
        {
            "total": total,
            "count_above": count_above,
            "above_ratio": count_above / total,
            "count_below": count_below,
            "below_ratio": count_below / total,
        }
    )


def calculate_abnormal_read_fraction(
    feature_file: Path,
    dmr_file: Path,
    output_file: Path,
    feature: str = "average",
) -> None:
    """Main calculation routine."""
    logging.info("Reading feature file: %s", feature_file)
    feature_df = read_feature_file(feature_file)

    logging.info("Reading DMR/reference file: %s", dmr_file)
    dmr_df = read_dmr_file(dmr_file)

    logging.info("Merging feature table with DMR regions")
    merged_df = pd.merge(feature_df[["keys", feature]], dmr_df, on="keys")

    logging.info("Extracting read-level values from feature column: %s", feature)
    merged_df["values"] = merged_df[feature].apply(lambda item: extract_feature_values(item, feature))

    logging.info("Counting abnormal reads")
    abnormal_df = merged_df.apply(
        lambda row: count_abnormal(row["values"], row["ref_min"], row["ref_max"]),
        axis=1,
    )
    merged_df = pd.concat([merged_df, abnormal_df], axis=1)

    logging.info("Writing output: %s", output_file)
    merged_df.to_csv(output_file, sep="\t", header=True, index=False)


def main() -> None:
    args = parse_args()
    setup_logging(args.verbose)

    feature_file = Path(args.feature_file)
    dmr_file = Path(args.dmr_file)
    if args.output is None:
        output_file = Path(f"{feature_file.stem}_abnormal_reads.txt")
    else:
        output_file = Path(args.output)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    calculate_abnormal_read_fraction(
        feature_file=feature_file,
        dmr_file=dmr_file,
        output_file=output_file,
        feature=args.feature,
    )


if __name__ == "__main__":
    main()
