#!/usr/bin/env python3
"""
Summarize read-level methylation features across genomic bins.

This script aggregates per-read feature values generated by
methyl_read_bin_profiler.py across multiple samples. For each genomic bin and
feature type, it calculates summary statistics after removing outliers by a
z-score threshold.

The output format is intentionally kept consistent with the original analysis
script:
    chr  start  end  min  median  mean  max  std  outlier_number  outlier_values  count_after_filtering
"""

from __future__ import annotations

import argparse
from decimal import Decimal
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

import numpy as np
import pandas as pd


DEFAULT_FEATURES = ("average", "mhl", "transitions_score")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Aggregate read-level methylation features across genomic bins "
            "from multiple per-sample text files."
        )
    )
    parser.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing per-sample bin-level feature files.",
    )
    parser.add_argument(
        "--output-prefix",
        required=True,
        help="Prefix for output files. One file will be generated per feature type.",
    )
    parser.add_argument(
        "--file-keyword",
        default="cts_aver_mhl_ts_4cpg",
        help=(
            "Keyword used to select input .txt files. "
            "Default: cts_aver_mhl_ts_4cpg"
        ),
    )
    parser.add_argument(
        "--features",
        nargs="+",
        default=list(DEFAULT_FEATURES),
        choices=list(DEFAULT_FEATURES),
        help="Feature types to summarize. Default: average mhl transitions_score",
    )
    parser.add_argument(
        "--zscore-threshold",
        type=float,
        default=3.0,
        help="Absolute z-score threshold for outlier removal. Default: 3.0",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print progress information.",
    )
    return parser.parse_args()


def find_input_files(input_dir: Path, file_keyword: str) -> List[Path]:
    """Return sorted .txt files containing the requested keyword."""
    files = sorted(
        path for path in input_dir.iterdir()
        if path.is_file() and path.suffix == ".txt" and file_keyword in path.name
    )
    if not files:
        raise FileNotFoundError(
            f"No .txt files containing '{file_keyword}' were found in: {input_dir}"
        )
    return files


def read_feature_values(feature_string: str, feature_name: str) -> List[float]:
    """
    Parse feature values from strings such as 'average:0.123:0.456'.

    If the field only contains the feature label, the original script treated it
    as an empty feature list. This behavior is preserved.
    """
    if feature_string == feature_name:
        return []
    values = feature_string.replace(f"{feature_name}:", "").split(":")
    return [float(Decimal(value)) for value in values if value != ""]


def initialize_bins(first_file: Path) -> Tuple[pd.DataFrame, List[List[float]], List[List[int]]]:
    """Initialize genomic-bin metadata and per-bin containers from the first file."""
    region_df = pd.read_csv(first_file, header=None, sep="\t", usecols=[0, 1, 2])
    number_of_bins = region_df.shape[0]
    feature_values = [[] for _ in range(number_of_bins)]
    count_values = [[] for _ in range(number_of_bins)]
    return region_df, feature_values, count_values


def collect_values(
    input_files: Sequence[Path],
    feature_name: str,
    feature_values: List[List[float]],
    count_values: List[List[int]],
    verbose: bool = False,
) -> None:
    """Collect read-level feature values for a given feature across all files."""
    feature_to_column = {
        "average": 4,
        "mhl": 5,
        "transitions_score": 6,
    }
    feature_col = feature_to_column[feature_name]

    for input_file in input_files:
        if verbose:
            print(f"Reading {input_file}")
        with input_file.open("r", encoding="utf-8") as handle:
            for line_index, line in enumerate(handle):
                fields = line.rstrip("\n").split("\t")
                if len(fields) != 8:
                    raise ValueError(
                        f"Expected 8 tab-separated columns in {input_file}, "
                        f"line {line_index + 1}, but found {len(fields)}."
                    )
                count_values[line_index].append(int(fields[7]))
                feature_values[line_index].extend(
                    read_feature_values(fields[feature_col], feature_name)
                )


def summarize_one_bin(
    values: Sequence[float],
    count_values: Sequence[int],
    zscore_threshold: float,
) -> List[object]:
    """
    Summarize one genomic bin after z-score based outlier removal.

    The order and content of returned fields match the original script:
    min, median, mean, max, std, outlier_number, outlier_values, count_after_filtering.
    """
    if not values:
        return [0, 0, 0, 0, 0, 0, 0, 0]

    array = np.asarray(values, dtype=float)
    mean_value = np.mean(array)
    std_value = np.std(array)

    filtered_values: List[float] = []
    outlier_number = 0
    outlier_values = "outlier"

    for value in array:
        if std_value == 0:
            filtered_values.append(float(value))
            continue
        z_score = (value - mean_value) / std_value
        if abs(z_score) > zscore_threshold:
            outlier_number += 1
            outlier_values += f":{value}"
        else:
            filtered_values.append(float(value))

    filtered = np.asarray(filtered_values, dtype=float)
    return [
        np.min(filtered),
        np.median(filtered),
        np.mean(filtered),
        np.max(filtered),
        np.std(filtered),
        outlier_number,
        outlier_values,
        len(filtered),
    ]


def summarize_feature(
    input_files: Sequence[Path],
    feature_name: str,
    output_prefix: str,
    zscore_threshold: float,
    verbose: bool = False,
) -> Path:
    """Summarize one feature type and write the corresponding output file."""
    if verbose:
        print(f"Calculation type: {feature_name}")

    region_df, feature_values, count_values = initialize_bins(input_files[0])
    collect_values(input_files, feature_name, feature_values, count_values, verbose)

    summary_rows = [
        summarize_one_bin(values, counts, zscore_threshold)
        for values, counts in zip(feature_values, count_values)
    ]
    summary_df = pd.DataFrame(summary_rows)
    merged_df = pd.concat([region_df, summary_df], axis=1)

    output_path = Path(f"{output_prefix}_{feature_name}.txt")
    merged_df.to_csv(output_path, sep="\t", header=False, index=False)

    if verbose:
        print(f"Wrote {output_path}")
    return output_path


def main() -> None:
    args = parse_args()
    input_dir = Path(args.input_dir).resolve()
    input_files = find_input_files(input_dir, args.file_keyword)

    if args.verbose:
        print("Input files:")
        for input_file in input_files:
            print(f"  {input_file}")

    for feature_name in args.features:
        summarize_feature(
            input_files=input_files,
            feature_name=feature_name,
            output_prefix=args.output_prefix,
            zscore_threshold=args.zscore_threshold,
            verbose=args.verbose,
        )


if __name__ == "__main__":
    main()
